<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>

 <div class='bubbles'>
      <span style='--i:11;'></span>
      <span style='--i:12;'></span>
      <span style='--i:24;'></span>
      <span style='--i:10;'></span>
      <span style='--i:14;'></span>
      <span style='--i:23;'></span>
      <span style='--i:18;'></span>
      <span style='--i:16;'></span>
      <span style='--i:19;'></span>
      <span style='--i:20;'></span>
      <span style='--i:22;'></span>
      <span style='--i:25;'></span>
      <span style='--i:18;'></span>
      <span style='--i:21;'></span>
      <span style='--i:15;'></span>
      <span style='--i:13;'></span>
      <span style='--i:28;'></span>
      <span style='--i:11;'></span>
      <span style='--i:12;'></span>
      <span style='--i:24;'></span>
      <span style='--i:10;'></span>
      <span style='--i:14;'></span>
      <span style='--i:23;'></span>
      <span style='--i:18;'></span>
      <span style='--i:16;'></span>
      <span style='--i:19;'></span>
      <span style='--i:20;'></span>
      <span style='--i:22;'></span>
      <span style='--i:25;'></span>
      <span style='--i:18;'></span>
      <span style='--i:21;'></span>
      <span style='--i:15;'></span>
      <span style='--i:13;'></span>
      <span style='--i:28;'></span>
      <span style='--i:11;'></span>
      <span style='--i:12;'></span>
      <span style='--i:24;'></span>
      <span style='--i:10;'></span>
      <span style='--i:14;'></span>
      <span style='--i:23;'></span>
      <span style='--i:18;'></span>
      <span style='--i:16;'></span>
      <span style='--i:19;'></span>
      <span style='--i:20;'></span>
      <span style='--i:22;'></span>
      <span style='--i:25;'></span>
      <span style='--i:18;'></span>

    </div>
